# Dependencies
highlighter:      rouge
layout: default
comments: true
# other options
gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# SetupeTdataEdge
title:            'Habte Tadesse'
name:             'Habte Tadesse'
#tagline:          ''
description:      'Statistics'
url:              'https://habtestat.github.io'
baseurl:          'https://habtestat.github.io'
# blogurl:          /blog/

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'Habte Tadesse'
  url:            'habtestat.github.io'
  email:          'habte.tade@yahoo.com'
  github:         'https://github.com/habtestat'
  github_io_url:  "http://mesfind.github.io"
  facebook:       'https://www.facebook.com/habtestat'
  twitter:        'https://twitter.com/habtestat'
  googleplus:     'https://www.google.com/habtestat'
  linkedin:       'https://www.linkedin.com/in/habtestat'
  slack:          'https://habtestat.slack.com'
  disqus_shortname: habtestat
  gravatar_md5: ''

paginate:         3
# paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0

github:           
  repo:           https://github.com/habtestat/habtestat.github.io

# Collections
collections:
  - projects
  - talks

feed:
  path: atom.xml
# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
# Default Settings
